### ISSUE TITLE
مشخص شدن لایسنس مستندات

### ISSUE THREAD

**Issue by mhaghighat20** [AdvProg2020/Documents#20]
برای این که دیگران بتونن قانونی و درست از مستندات این ریپو استفاده کنن لازمه براش لایسنس تعیین کنیم
پیشنهاد من
https://choosealicense.com/licenses/cc0-1.0/
یا
https://choosealicense.com/licenses/mit/
هست

**Comment by ahmadsalimi** [comment]
انجام شد
